### ISSUE TITLE
prompt visualization with hover info

### ISSUE THREAD

**Issue by jettjaniak** [jettjaniak/tinyevals#3]
- in tinyevals/vis.py
- hover info work with many prompts at once
- currently when you visualise many prompts the hover info only shows below the first one
- even if you run it in separate cells
- it looks like they appear in the same "HTML context"

**Comment by jaidhyani** [comment]
Yup, it's the same HTML document as far as this js is concerned. It looks like this is the same issue from here: https://stackoverflow.com/questions/77199552/how-to-fix-ipython-display-bug-in-vscode

The 'hover_info' div gets matched by the first occurrence in the notebook and stops looking. Confirmed that using a unique id fixes it.

**Comment by jettjaniak** [comment]
moved https://github.com/delphi-suite/delphi/issues/9 please accept the invite and assign yourself
