### ISSUE TITLE
top k predictions for models comparison

### ISSUE THREAD

**Issue by jettjaniak** [jettjaniak/tinyevals#4]
- in notebooks/intro/03 we had probability of next token and top 3 predictions shown
- in 04 I'm just showing next probability in model a and model b
- but I'd like to add top 3 predictions for model b that also show what were the probabilities of these tokens on model a
- in tinyevals/inference.py
	- function that
		- takes
			- two models: A and B
			- tokenized prompt
			- tokenizer
		- returns: a list; each element contains
			- probabilities of next token for both models
			- top k token predictions according to model B
			- probabilities of these tokens according to both models
	- first element corresponds to prediction of EOS / BOS so should be None or something
		- don't make the same mistake as I did returning a list shorter by one
	- make sure it works with models on any device (cpu/mps/cuda), as long as both models are on the same one
	- use `next` rather than `correct` in names
		- I was inconsistent about that
- in tinyevals/vis.py
	- function that combines the vis with hover from the same file and the new function in inference.py
	- takes the same arguments and returns a visualisation that is a combination of what was in notebooks 03 & 04
	- this part depends on #3

**Comment by siwei-li** [comment]
Quick question: I have something like below now, how should I handle the EOS at the beginning? 
<img width="390" alt="image" src="https://github.com/jettjaniak/tinyevals/assets/46750682/4dfa92af-7a00-46e2-90e6-74787fd5a786">

**Comment by jettjaniak** [comment]
> - first element corresponds to prediction of EOS / BOS so should be None or something
>   - don't make the same mistake as I did returning a list shorter by one

Actually, the first token doesn't have to be EOS/BOS, but still model doesn't return a prediction for the first one. I'd go with None.

**Comment by siwei-li** [comment]
> Actually, the first token doesn't have to be EOS/BOS, but still model doesn't return a prediction for the first one. I'd go with None. 

<img width="264" alt="image" src="https://github.com/jettjaniak/tinyevals/assets/46750682/f472c6f6-2818-41c7-9b91-78bb2c3b59ea">

Not sure if this is good enough?

**Comment by jettjaniak** [comment]
Oh, sorry. I thought you were asking about the function in inference.py not the visualization. We don't need to display anything.

**Comment by siwei-li** [comment]
Sorry I was confused... I thought for just the visualization purpose I could do with returning a list shorter by one, are you suggesting returning something like
`torch.cat((torch.tensor([None]), probs))`

so that later we don't have to shift the indices by one?

**Comment by jettjaniak** [comment]
Don't return a shorter list, it's cursed.

**Comment by jettjaniak** [comment]
moved https://github.com/delphi-suite/delphi/issues/9 please accept the invite and assign yourself
