### ISSUE TITLE
map tokens to prompts and positions

### ISSUE THREAD

**Issue by jettjaniak** [jettjaniak/tinyevals#7]
- for each token in the tokenizer
- list of all (prompt_idx, pos_idx) where this token appears in the validation split of tinystories-v2-clean-tokenized
- basically `dict[int, list[tuple[int, int]]]`
- for now try it on a subset of train split of https://huggingface.co/datasets/jbrinkma/tinystories-v2-clean-tokenized

**Comment by menamerai** [comment]
@jettjaniak should we access each token from the vocab/tokenizer directly, or should we just run through the tokenized dataset and map each existing token present in the dataset assuming they all correspond to the tokenizer we use?

**Comment by jettjaniak** [comment]
the tokenized dataset works now, including the validation split

**Comment by jettjaniak** [comment]
moved https://github.com/delphi-suite/delphi/issues/8 please accept the invite and assign yourself
